### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by basavarajarani** [mooyoul/serverless-latest-layer-version#10]
Hi,

I'm trying to use this plugin to substitute the latest version of the lambda layer into the function. However i'm continuously getting the error 

 An error occurred: FLSLSDPersistLsdTestResultsLambdaLambdaFunction - 1 validation error detected: Value '[arn:aws:lambda:ap-southeast-2:xxxxxxxxxxxx:layer:oraclelib:latest]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+)] (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: 6b295596-80c7-425b-b8f3-7c03673b333c).

I tried with both versions 2.0.0 and 2.1.0. Its the same outcome.

Can you please suggest if I'm doing something incorrect?
--
Update -
I've even tried exporting the aws profile and executing the sls deploy. But still getting the same error.

Thanks,
Bas

**Comment by mooyoul** [comment]
Hmm. That's weird. That error actually means that layer version replacements never happened. 
1) Could you provide your current `serverless.yml` contents?
2) Could you double-check that layer really exists?
3) Could you attach full serverless logs? I want to see logs from this plugin.

**Comment by basavarajarani** [comment]
Hi,

Apologies for responding late. I believe it was a mistake in our serverless.yml file. The plugin we were referring to was "serverless-aws-latest-layer-version". When we updated it to "serverless-latest-layer-version", it worked fine.

Thanks for your help.

Regards,
Bas
