### ISSUE TITLE
Conflict when used together with the "serverless-pseudo-parameters" plugin.

### ISSUE THREAD

**Issue by danielpereirabp** [mooyoul/serverless-latest-layer-version#2]
Ex.:

layers:
    - arn:aws:lambda:**#{AWS::Region}**:**#{AWS::AccountId}**:layer:MyLayerName:latest

Function "processLayerARNList":

const arnParts = arn.split (':');
const layerRegion = arnParts [3];
const layerVersion = arnParts [7];

arnParts: [ 'arn', 'aws', 'lambda', '#{AWS', '', 'Region}', '#{AWS', '', 'AccountId}', 'layer', 'MyLayerName', 'latest' ]

arnParts [3]: '#{AWS'
arnParts [7]: ''

**Comment by andrepintorj** [comment]
There is a PR addressing this issue already created but still not merged by maintainer: https://github.com/mooyoul/serverless-latest-layer-version/pull/4

**Comment by mooyoul** [comment]
Hello there, This issue has been fixed from v2.0.0. Now this plugin resolves pseudo parameters in layer ARN. Would you try again with v2.0.0 release? Thanks!
